name: test_coverage

on:
  push:
    branches:
      - main
      - im3tests

jobs:
  build:
    runs-on: windows-latest
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GH_PAT}}

    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v2-branch
        with:
          r-version: '3.6'
      - uses: r-lib/actions/setup-pandoc@v2-branch
      - uses: r-lib/actions/setup-tinytex@v2-branch
      
      - name: Cache R packages 
        uses: actions/cache@v1 
        with: 
          path: ${{ env.R_LIBS_USER }} 
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }} 
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1- 
      
      - name: Install dependencies
        run: |
          install.packages(c("remotes","rcmdcheck"), repos = "https://cloud.r-project.org")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        
      - name: Test coverage
        run: |
          remotes::install_cran("covr")
          covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")
        shell: Rscript {0}
